### ISSUE TITLE
Error in line 245 and 56 while creating discovery rules 

### ISSUE THREAD

**Issue by gsurendran26** [13hakta/zbxwmi#13]
Hi All,

I'm facing the following error while creating/testing for the windows hostname, as I'm using the Ubuntu 22.04.4 LTS platform with Python 3.10.12 version, please assist with this and let me know for any further details.

Traceback (most recent call last):
File "/usr/lib/zabbix/externalscripts/zbxwmi", line 245, in <module>
main()
File "/usr/lib/zabbix/externalscripts/zbxwmi", line 56, in main
fieldlist = options.fields.split(',')
AttributeError: 'NoneType' object has no attribute 'split'

![Error](https://github.com/13hakta/zbxwmi/assets/44574373/bbb82876-c53f-4475-b579-39bacb888fa2)

Thanks,
Surendran

**Comment by electricbs** [comment]
same issue.  did you ever resolve?

**Comment by saad8281** [comment]
Please keep following the error mentioned by the Zabbix, and provide the key of the discovery rule according to python script query. 

AttributeError: 'None Type' means that options.fields.split query in the scipt is getting the value 'None Type' which is not allowed in python. 

so mention "-fields","VolumeName" in the key(zabbix front end), it will take fields =VolumerName instead of 'None Type'

Note: you can query other available fields from windows server by using command e.g. Get-WmiObject -Class Win32_LogicalDisk | get-member.
