### ISSUE TITLE
Multiple Error

### ISSUE THREAD

**Issue by ghost** [13hakta/zbxwmi#3]
From Zabbix Item link to the host

Preprocessing failed for: Traceback (most recent call last):. File "/usr/lib/zabbix/externalscripts/zbxwmi", line 224, in ...
1. Failed: cannot extract value from json by path "$[7].PercentProcessorTime": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "/usr/lib/zabbix/externalscripts/zbxwmi", line 224, in <module>
main()
File "/usr/lib/zabbix/externalsc

Python 3.6.9

**Comment by Francois3362** [comment]
Hello, 
I have the same error.
Did you find a solution?
Thanks a lot.
![2020-01-15 16_58_17-Configuration des éléments](https://user-images.githubusercontent.com/59927676/72449013-49ce7a00-37b8-11ea-9805-4d3a57a46ea9.png)

**Comment by 13hakta** [comment]
Hello.
Please show what in "Processors" string. In a working environment I have this:

`[{"Name": "0", "PercentProcessorTime": "None"},{"Name": "1", "PercentProcessorTime": "29"},{"Name": "2", "PercentProcessorTime": "52"},{"Name": "3", "PercentProcessorTime": "17"}]`

**Comment by Francois3362** [comment]
Sorry, it was a problem with impacket... it's ok now.
Did you work with the memory load script?
I tried to configure it but zabbix deamon stopped...
Can you give me your configuration for memory load?
Thks.

**Comment by Francois3362** [comment]
I have 197 servers running with this template.
For a lot of this servers I have no information for processors part.
